apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app_name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app_label }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app_label }}
  template:
    metadata:
      labels:
        app: {{ .Values.app_label }}
    spec:
      containers:
      - name: {{ .Values.container.name }}
        image: {{ .Values.container.image }}:{{ .Values.container.image_tag }}
        ports:
        - containerPort: {{ .Values.container.port }}
        envFrom:
        - configMapRef:
            name: {{ .Values.app_name }}-configmap
        - secretRef:
            name: {{ .Values.app_name }}-secret
        volumeMounts:
          - name: {{ .Values.container.volume.name }}
            mountPath: {{ .Values.container.volume.mountPath }}
      volumes:
        - name: {{ .Values.container.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.app_name }}-pvc