apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app_name }}-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.volume.accessMode }}
  volumeMode: {{ .Values.volume.mode }}
  resources:
    requests:
      storage: {{ .Values.volume.storage }}
  storageClassName: {{ .Values.volume.storageClassName }}