apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.service }}
  name: {{ .Values.appName }}-service
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.servicePort }}
    protocol: TCP
    targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ .Values.app }}