apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-ns
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-pod-detyra
        image: nginx:1.16.1
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: env-configmap
        - secretRef:
            name: env-secret