apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    app: cimi-nginx
    training: appsteallar
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      training: appsteallar
  template:
    metadata:
      labels:
        training: appsteallar
    spec:
      containers:
      - name: nginx
        image: nginx
